server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_ai_user?useUnicode=true&characterEncoding=utf8
    username: root
    password: qlj11280108
  redis:
    host: localhost
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

jwt:
  secret: testAiUserServiceSecretKey2024
  expiration: 86400000